# Generated by Django 2.2.2 on 2019-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=30)),
                ('good_desc', models.CharField(max_length=100)),
                ('good_price', models.CharField(max_length=10)),
            ],
        ),
    ]
