# Generated by Django 2.2.2 on 2019-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190615_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
